services:
  - type: web
    name: planning-poker-backend
    runtime: node
    plan: free
    buildCommand: npm install && cd server && npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 